We use elemental PyTorch to implement linear regression here. However, in most actual applications, abstractions such as <code>nn.Moudle</code> or <code>nn.Lienear</code> are used.

In [ ]:
nums = [0, 1, 2, 3 , 4]
print(nums)
print(nums[2: 4])

[0, 1, 2, 3, 4]
[2, 3]


In [ ]:
import numpy as np
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(b)
print(b[:, :])
print(b[1:2, 1:2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[6]]


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [14]:
import numpy as np
import pandas as pd
xy = np.loadtxt('/content/drive/MyDrive/NLP/data-01-test-score.csv', delimiter=',', dtype=np.float32)
data = pd.read_csv(filepath_or_buffer='/content/drive/MyDrive/NLP/data-01-test-score.csv')

In [16]:
print(type(xy))
print(xy.shape)
print(xy.size)
print(xy)
print(data.head())
print(data.shape)

<class 'numpy.ndarray'>
(25, 4)
100
[[ 73.  80.  75. 152.]
 [ 93.  88.  93. 185.]
 [ 89.  91.  90. 180.]
 [ 96.  98. 100. 196.]
 [ 73.  66.  70. 142.]
 [ 53.  46.  55. 101.]
 [ 69.  74.  77. 149.]
 [ 47.  56.  60. 115.]
 [ 87.  79.  90. 175.]
 [ 79.  70.  88. 164.]
 [ 69.  70.  73. 141.]
 [ 70.  65.  74. 141.]
 [ 93.  95.  91. 184.]
 [ 79.  80.  73. 152.]
 [ 70.  73.  78. 148.]
 [ 93.  89.  96. 192.]
 [ 78.  75.  68. 147.]
 [ 81.  90.  93. 183.]
 [ 88.  92.  86. 177.]
 [ 78.  83.  77. 159.]
 [ 82.  86.  90. 177.]
 [ 86.  82.  89. 175.]
 [ 78.  83.  85. 175.]
 [ 76.  83.  71. 149.]
 [ 96.  93.  95. 192.]]
   73  80   75  152
0  93  88   93  185
1  89  91   90  180
2  96  98  100  196
3  73  66   70  142
4  53  46   55  101
(24, 4)


In [19]:
y_data = xy[: ,[-1]]
print(y_data.shape)
print(len(y_data))
print(y_data[:5])
print(y_data)

(25, 1)
25
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [21]:
x_data = xy[:, 0:-1]

In [20]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [22]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    hypothesis = x_train.matmul(W) + b
    cost = torch.mean((hypothesis - y_train) ** 2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/20 Cost: 26811.960938
Epoch    1/20 Cost: 9920.530273
Epoch    2/20 Cost: 3675.298340
Epoch    3/20 Cost: 1366.260498
Epoch    4/20 Cost: 512.542480
Epoch    5/20 Cost: 196.896637
Epoch    6/20 Cost: 80.190987
Epoch    7/20 Cost: 37.038696
Epoch    8/20 Cost: 21.081343
Epoch    9/20 Cost: 15.178760
Epoch   10/20 Cost: 12.993679
Epoch   11/20 Cost: 12.183023
Epoch   12/20 Cost: 11.880535
Epoch   13/20 Cost: 11.765958
Epoch   14/20 Cost: 11.720851
Epoch   15/20 Cost: 11.701438
Epoch   16/20 Cost: 11.691514
Epoch   17/20 Cost: 11.685116
Epoch   18/20 Cost: 11.680005
Epoch   19/20 Cost: 11.675380
Epoch   20/20 Cost: 11.670952


In [23]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)
    def forward(self, x):
        return self.linear(x)

In [24]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)
model = MultivariateLinearRegressionModel()
optimizer = optim.SGD(model.parameters(), lr=1e-5)
nb_epochs = 20
for epoch in range(nb_epochs + 1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print(f'Epoch {epoch:4d}/{nb_epochs:.6f} Cost: {cost.item()}')

Epoch    0/20.000000 Cost: 27006.34765625
Epoch    1/20.000000 Cost: 9993.474609375
Epoch    2/20.000000 Cost: 3703.342529296875
Epoch    3/20.000000 Cost: 1377.7034912109375
Epoch    4/20.000000 Cost: 517.8475952148438
Epoch    5/20.000000 Cost: 199.9321746826172
Epoch    6/20.000000 Cost: 82.38700103759766
Epoch    7/20.000000 Cost: 38.924530029296875
Epoch    8/20.000000 Cost: 22.8522891998291
Epoch    9/20.000000 Cost: 16.907072067260742
Epoch   10/20.000000 Cost: 14.706093788146973
Epoch   11/20.000000 Cost: 13.889427185058594
Epoch   12/20.000000 Cost: 13.584648132324219
Epoch   13/20.000000 Cost: 13.46911334991455
Epoch   14/20.000000 Cost: 13.423510551452637
Epoch   15/20.000000 Cost: 13.403780937194824
Epoch   16/20.000000 Cost: 13.393638610839844
Epoch   17/20.000000 Cost: 13.387019157409668
Epoch   18/20.000000 Cost: 13.381743431091309
Epoch   19/20.000000 Cost: 13.376914024353027
Epoch   20/20.000000 Cost: 13.372291564941406
